EMPManegment.WebApplication/Controllers/EmpAddDetailsController.cs
using EMPManagment.Web.Helper;
using EMPManagment.Web.Models.API;
using EMPManegment.EntityModels.View_Model;
using EMPManegment.EntityModels.ViewModels;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics.Metrics;
using System.Security.Claims;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using EMPManegment.EntityModels.Crypto;

namespace EMPManegment.WebApplication.Controllers
{
    [AllowAnonymous]
    public class EmpAddDetailsController : Controller
    {

        public EmpAddDetailsController(WebAPI webAPI, IWebHostEnvironment environment, APIServices aPIServices)
        {
            WebAPI = webAPI;
            Environment = environment;
            APIServices = aPIServices;
        }

        public WebAPI WebAPI { get; }
        public IWebHostEnvironment Environment { get; }
        public APIServices APIServices { get; }

        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> AddEmpDetail()
        {
            try
            { 
                HttpClient client = WebAPI.Initil();
                ApiResponseModel AddUserResponse = await APIServices.GetAsync("","AddEmp/CheckUser");
                if (AddUserResponse.code == 200)
                {
                    ViewBag.EmpId = AddUserResponse.data;
                }
                
                return View();

            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpPost]
        public async Task<IActionResult> AddEmpDetail(LoginDetailsView AddEmployee)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var path = Environment.WebRootPath;
                    var filepath = "Content/Image/" + AddEmployee.Image.FileName;
                    var fullpath = Path.Combine(path, filepath);
                    UploadFile(AddEmployee.Image, fullpath);
                    Crypto.Hash(AddEmployee.Password,
                        out byte[] passwordHash,
                        out byte[] passwordSalt);
                    var AddUser = new EmpDetailsView()
                    {
                        UserName = AddEmployee.UserName,
                        DepartmentId = AddEmployee.DepartmentId,
                        FirstName = AddEmployee.FirstName,
                        LastName = AddEmployee.LastName,
                        Address = AddEmployee.Address,
                        CityId = AddEmployee.CityId,
                        StateId = AddEmployee.StateId,
                        CountryId = AddEmployee.CountryId,
                        DateOfBirth = AddEmployee.DateOfBirth,
                        Email = AddEmployee.Email,
                        Gender = AddEmployee.Gender,
                        PhoneNumber = AddEmployee.PhoneNumber,
                        CreatedOn = DateTime.Now,
                        PasswordHash = passwordHash,
                        PasswordSalt = passwordSalt,
                        Image = filepath,
                        IsActive = AddEmployee.IsActive,
                    };
                    ApiResponseModel postuser = await APIServices.PostAsync(AddUser, "AddEmp/AddEmployees");
                    ViewBag.Name = HttpContext.Session.GetString("UserName");
                    if (postuser.code == 200)
                    {
                        var identity = new ClaimsIdentity(new[] { new Claim(ClaimTypes.Name, AddEmployee.UserName) }, CookieAuthenticationDefaults.AuthenticationScheme);
                        var principal = new ClaimsPrincipal(identity);
                        HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                        return RedirectToAction("Login", "UserLogin");
                    }
                    else
                    {
                        TempData["ErrorMessage"] = postuser.message;
                        return View();
                    }
                }
                HttpClient client = WebAPI.Initil();
                ApiResponseModel addEmpResponse = await APIServices.GetAsync("", "AddEmp/CheckUser");
                if (addEmpResponse.code == 200)
                {
                    ViewBag.EmpId = addEmpResponse.data;
                }
                return View();  
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }
       
        public async Task<JsonResult> GetDepartment()
        {

            try
            {
                List<Department> getDepartment = new List<Department>();
                HttpClient client = WebAPI.Initil();
                ApiResponseModel response = await APIServices.GetAsync(null,"AddEmp/GetDepartment");
                if (response.code == 200)
                {
                    getDepartment = JsonConvert.DeserializeObject<List<Department>>(response.data.ToString());
                }
                return new JsonResult(getDepartment);

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public async Task<JsonResult> GetCountrys()
        {

            try
            {
                List<CountryView> countries = new List<CountryView>();
                HttpClient client = WebAPI.Initil();
                ApiResponseModel response = await APIServices.GetAsyncId(null,"CSC/GetCountries");
                if (response.code == 200)
                {
                    countries = JsonConvert.DeserializeObject<List<CountryView>>(response.data.ToString());
                }
                return new JsonResult(countries);

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public async Task<JsonResult> GetState(int StateId)
        {

            try
            {
                List<StateView> states = new List<StateView>();
                HttpClient client = WebAPI.Initil();
                ApiResponseModel response = await APIServices.GetAsyncId(null, "CSC/GetState?StateId="+StateId);
                if (response.code == 200)
                {
                    states = JsonConvert.DeserializeObject<List<StateView>>(response.data.ToString());
                }
                return new JsonResult(states);

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public async Task<JsonResult> GetCity(int CityId)
        {

            try
            {
                List<CityView> cities = new List<CityView>();
                HttpClient client = WebAPI.Initil();
                ApiResponseModel response = await APIServices.GetAsyncId(null, "CSC/GetCities?CityId="+ CityId);
                if (response.code == 200)
                {
                    cities = JsonConvert.DeserializeObject<List<CityView>>(response.data.ToString());
                }
                return new JsonResult(cities);

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public async Task<JsonResult> GetQuestion()
        {

            try
            {
                List<QuestionView> questions = new List<QuestionView>();
                HttpClient client = WebAPI.Initil();
                ApiResponseModel response = await APIServices.GetAsync(null, "CSC/GetQuestion");
                if (response.code == 200)
                {
                    questions = JsonConvert.DeserializeObject<List<QuestionView>>(response.data.ToString());
                }
                return new JsonResult(questions);

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }


        public void UploadFile(IFormFile ImageFile, string ImagePath)
        {
            FileStream stream = new FileStream(ImagePath, FileMode.Create);
            ImageFile.CopyTo(stream);
        }
    }
}

EMPManegment.WebApplication/Controllers/UserLoginController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Newtonsoft.Json;
using static Azure.Core.HttpHeader;
using EMPManagment.Web.Helper;
using EMPManagment.Web.Models.API;
using EMPManegment.EntityModels.ViewModels;
using EMPManegment.EntityModels.View_Model;

namespace EMPManegment.Web.Controllers
{
    public class UserLoginController : Controller
    {

        public UserLoginController(WebAPI webAPI, APIServices aPIServices, IWebHostEnvironment environment)
        {
            WebAPI = webAPI;
            APIServices = aPIServices;
            Environment = environment;
        }

        public WebAPI WebAPI { get; }
        public APIServices APIServices { get; }
        public IWebHostEnvironment Environment { get; }

        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Login()
        {
                return View();
        }
        

        [HttpPost]
        public async Task<IActionResult> Login(LoginRequest login)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    ApiResponseModel responsemodel = await APIServices.PostAsync(login, "UserLogin/Login");
                    LoginResponseModel userlogin = new LoginResponseModel();
                    if (responsemodel.code != (int)HttpStatusCode.OK)
                    {
                       

                        if (responsemodel.code == (int)HttpStatusCode.Forbidden)
                        { 
                            TempData["ErrorMessage"] = responsemodel.message;
                            return Ok(new { Message = string.Format(responsemodel.message), Code = responsemodel.code });
                        }
                        else
                        {
                            TempData["ErrorMessage"] = responsemodel.message;
                        }
                    }

                    else
                    {
                        var data = JsonConvert.SerializeObject(responsemodel.data);
                        userlogin.Data = JsonConvert.DeserializeObject<LoginView>(data);
                        var claims = new List<Claim>()
                        {
                            new Claim("UserID", userlogin.Data.Id.ToString()),
                            new Claim("FirstName", userlogin.Data.FirstName),
                            new Claim("Fullname", userlogin.Data.FullName),
                            new Claim("UserName", userlogin.Data.UserName),
                            new Claim("ProfileImage", userlogin.Data.ProfileImage),
                            new Claim("IsAdmin", userlogin.Data.IsAdmin.ToString()),

                        };

                        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                        var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);
                        HttpContext.Session.SetString("UserID", userlogin.Data.Id.ToString());
                        HttpContext.Session.SetString("FirstName", userlogin.Data.FirstName);
                        HttpContext.Session.SetString("FullName", userlogin.Data.FullName);
                        HttpContext.Session.SetString("UserName", userlogin.Data.UserName);
                        HttpContext.Session.SetString("ProfileImage", userlogin.Data.ProfileImage);
                        HttpContext.Session.SetString("IsAdmin", userlogin.Data.IsAdmin.ToString());
                        return RedirectToAction("UserHome", "Home");
                    }  
                }
                return View();
            }
            catch (Exception ex)
            {
                return BadRequest(new { Message = "InternalServer" });
            }
        }
        public IActionResult Logout() 
        { 
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            var StoredCookies = Request.Cookies.Keys;
            foreach (var Cookie in StoredCookies)
            {
                Response.Cookies.Delete(Cookie);
            }
            return RedirectToAction("Login", "UserLogin");
        }



    }
}

EMPManegment.WebApplication/Views/UserLogin/Login.cshtml
@model EMPManegment.EntityModels.ViewModels.LoginRequest

<!DOCTYPE html>

<html lang="en">

<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<style>
    input[type=text] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        box-sizing: border-box;
        border: 3px solid #b3d9ff;
        -webkit-transition: 0.5s;
        transition: 0.5s;
        outline: none;
    }

        input[type=text]:focus {
            border: 3px solid #80bfff;
        }

    input[type=password] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        box-sizing: border-box;
        border: 3px solid #b3d9ff;
        -webkit-transition: 0.5s;
        transition: 0.5s;
        outline: none;
    }

        input[type=password]:focus {
            border: 3px solid #80bfff;
        }

</style>
<head>
    <title>Bonifatius</title>
    <meta charset="utf-8" />
    <meta name="description" content="
            The most advanced Bootstrap 5 Admin Theme with 40 unique prebuilt layouts on Themeforest trusted by 100,000 beginners and professionals. Multi-demo,
            Dark Mode, RTL support and complete React, Angular, Vue, Asp.Net Core, Rails, Spring, Blazor, Django, Express.js, Node.js, Flask, Symfony & Laravel versions.
            Grab your copy now and get life-time updates for free.
        " />
    <meta name="keywords" content="
            metronic, bootstrap, bootstrap 5, angular, VueJs, React, Asp.Net Core, Rails, Spring, Blazor, Django, Express.js,
            Node.js, Flask, Symfony & Laravel starter kits, admin themes, web design, figma, web development, free templates,
            free admin themes, bootstrap theme, bootstrap template, bootstrap dashboard, bootstrap dak mode, bootstrap button,
            bootstrap datepicker, bootstrap timepicker, fullcalendar, datatables, flaticon
        " />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta property="og:locale" content="en_US" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="
            Metronic - Bootstrap Admin Template, HTML, VueJS, React, Angular. Laravel, Asp.Net Core, Ruby on Rails,
            Spring Boot, Blazor, Django, Express.js, Node.js, Flask Admin Dashboard Theme & Template
        " />
    <meta property="og:url" content="https://keenthemes.com/metronic" />
    <meta property="og:site_name" content="Keenthemes | Metronic" />
    <link rel="canonical" href="https://preview.keenthemes.com/metronic8" />
    <link rel="shortcut icon" href="~/demo/assets/media/logos/favicon.ico" />


    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700" />

    <link href="~/demo/assets/plugins/global/plugins.bundle.css" rel="stylesheet" type="text/css" />
    <link href="~/demo/assets/css/style.bundle.css" rel="stylesheet" type="text/css" />

    <script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            }); var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                    '../../../../../../www.googletagmanager.com/gtm5445.html?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-5FS8GGP');</script>
    <script>
        if (window.top != window.self) {
            window.top.location.replace(window.self.location.href);
        }
    </script>
</head>
<body id="kt_body" class="auth-bg bgi-size-cover bgi-attachment-fixed bgi-position-center bgi-no-repeat">
    <script>
        var defaultThemeMode = "light";
        var themeMode;
        if (document.documentElement) {
            if (document.documentElement.hasAttribute("data-bs-theme-mode")) {
                themeMode = document.documentElement.getAttribute("data-bs-theme-mode");
            } else {
                if (localStorage.getItem("data-bs-theme") !== null) {
                    themeMode = localStorage.getItem("data-bs-theme");
                } else {
                    themeMode = defaultThemeMode;
                }
            }
            if (themeMode === "system") {
                themeMode = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
            }
            document.documentElement.setAttribute("data-bs-theme", themeMode);
        }
    </script>
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5FS8GGP" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

    <div class="d-flex flex-column flex-root">
        <style>
            body {
                background-image: url('~/demo/assets/media/auth/bg4.jpg');
            }

            [data-bs-theme="dark"] body {
                background-image: url('~/demo/assets/media/auth/bg4-dark.jpg');
            }
        </style>

        <div class="d-flex flex-column flex-column-fluid flex-lg-row">
            <div class="d-flex flex-center w-lg-50 pt-15 pt-lg-0 px-10">
                <div class="d-flex flex-center flex-lg-start flex-column">
                    <a asp-action="Login" asp-controller="UserLogin" class="mb-7">
                        <img alt="Logo" src="~/demo/assets/media/logos/1.png" />
                    </a>
                    <h2 class="text-white fw-normal m-0">
                       Bonifatius Technology 
                    </h2>
                </div>
            </div>

            <div class="d-flex flex-column-fluid flex-lg-row-auto justify-content-center justify-content-lg-end p-12 p-lg-20">

                <div class="bg-body d-flex flex-column align-items-stretch flex-center rounded-4 w-md-600px p-20">

                    <div class="d-flex flex-center flex-column flex-column-fluid px-lg-10 pb-15 pb-lg-20">


                        <form class="form w-100" asp-action="Login" asp-controller="UserLogin">

                            <div class="text-center mb-11">

                                <h1 class="text-dark fw-bolder mb-3">
                                    Log-In
                                </h1>
                            </div>
                            <div class="fv-row mb-8">
                                <input type="text" asp-for="UserName" placeholder="Emp-ID" class="form-control bg-transparent" />
                                <span asp-validation-for="UserName" class="text-danger"></span>
                            </div>
                            <div class="fv-row mb-3">
                                <input type="password" placeholder="Password" asp-for="Password" class="form-control bg-transparent" />
                                <span asp-validation-for="Password" class="text-danger"></span>
                                <span class="text-danger">@TempData["ErrorMessage"]</span>
                            </div>
                            <div class="d-flex flex-stack flex-wrap gap-3 fs-base fw-semibold mb-8">
                                <div></div>
                                <a href="reset-password.html" class="link-primary">
                                    Forgot Password ?
                                </a>
                            </div>
                            <div class="d-grid mb-10">
                                <button type="submit" id="kt_sign_in_submit" class="btn btn-primary">
                                    <span class="indicator-label">
                                        Sign In
                                    </span>

                                    <span class="indicator-progress">
                                        Please wait...    <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
                                    </span>
                                </button>
                            </div>

                            <div class="text-gray-500 text-center fw-semibold fs-6">
                                Not a Member yet???

                                <a class="link-primary">
                                    @Html.ActionLink("SingUp","AddEmpDetail","EmpAddDetails")
                                </a>
                            </div>

                        </form>

                    </div>

                </div>
            </div>

        </div>
    </div>
    <script>
        var hostUrl = "~/demo/assets/index.html";</script>
    <script src="~/demo/assets/plugins/global/plugins.bundle.js"></script>
    <script src="~/demo/assets/js/scripts.bundle.js"></script>
    <script src="~/demo/assets/js/custom/authentication/sign-in/general.js"></script>
</body>

</html>