EMPManegment.WebApplication/Controllers/InvoiceController.cs
using Microsoft.AspNetCore.Mvc;
using EMPManegment.EntityModels.ViewModels.SalesFolder;
using EMPManegment.EntityModels.ViewModels.TaskModels;
using Newtonsoft.Json;
using EMPManegment.EntityModels.ViewModels.Models;
using EMPManegment.EntityModels.ViewModels.Invoice;
using Microsoft.AspNetCore.Hosting;
using Aspose.Pdf.Operators;
using EMPManagment.Web.Helper;
using EMPManagment.Web.Models.API;
using EMPManegment.EntityModels.ViewModels.ProductMaster;
using EMPManegment.Web.Models;
using EMPManegment.EntityModels.ViewModels.VendorModels;
using EMPManegment.EntityModels.ViewModels.OrderModels;
using DinkToPdf.Contracts;
using Aspose.Pdf.Facades;
using DinkToPdf;
using Newtonsoft.Json.Converters;
using DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing;
using EMPManegment.EntityModels.ViewModels.DataTableParameters;
using Microsoft.AspNetCore.Components;
using EMPManegment.EntityModels.ViewModels.ProjectModels;
using EMPManegment.Web.Helper;
using Microsoft.AspNetCore.Authorization;
using Irony.Parsing.Construction;
using EMPManegment.EntityModels.ViewModels.ManualInvoice;
using Aspose.Foundation.UriResolver.RequestResponses;
using DocumentFormat.OpenXml.Spreadsheet;
using X.PagedList;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Mvc.Abstractions;
#nullable disable
namespace EMPManegment.Web.Controllers
{
    [Authorize]
    public class InvoiceController : Controller
    {
        public WebAPI WebAPI { get; }
        public IWebHostEnvironment Environment { get; }
        public APIServices APIServices { get; }
        public UserSession _userSession { get; }
        public IConverter PdfConverter { get; }

        public InvoiceController(WebAPI webAPI, IWebHostEnvironment environment, APIServices aPIServices, UserSession userSession, IConverter pdfConverter)
        {
            WebAPI = webAPI;
            Environment = environment;
            APIServices = aPIServices;
            _userSession = userSession;
            PdfConverter = pdfConverter;
        }
        public IActionResult Index()
        {
            return View();
        }

        [FormPermissionAttribute("Create Invoice-View")]
        public async Task<IActionResult> CreateInvoice(Guid? Id)
        {
            InvoiceMasterModel InvoiceDetails = new InvoiceMasterModel();
            if (Id != null)
            {
                ApiResponseModel Response = await APIServices.GetAsync("", "Invoice/DisplayInvoiceDetailsById?Id=" + Id);
                if (Response.code == 200)
                {
                    InvoiceDetails = JsonConvert.DeserializeObject<InvoiceMasterModel>(Response.data.ToString());
                    ViewBag.InvoiceNo = InvoiceDetails.InvoiceNo;
                    int rowNumber = 0;
                    foreach (var item in InvoiceDetails.InvoiceDetails)
                    {
                        item.RowNumber = rowNumber++;
                    }
                }
            }
            else
            {
                string porjectname = UserSession.ProjectName;
                ApiResponseModel Response = await APIServices.GetAsync("", "Invoice/CheckInvoiceNo?porjectname=" + porjectname);
                if (Response.code == 200)
                {
                    ViewBag.InvoiceNo = Response.data;
                }
            }
            return View(InvoiceDetails);
        }

        [HttpPost]
        public async Task<IActionResult> DisplayInvoiceProductDetailsListById()
        {
            try
            {
                string ProductId = HttpContext.Request.Form["ProductId"];
                var GetProduct = JsonConvert.DeserializeObject<InvoiceDetailsViewModel>(ProductId.ToString());
                List<InvoiceDetailsViewModel> Product = new List<InvoiceDetailsViewModel>();
                ApiResponseModel response = await APIServices.GetAsync("", "Invoice/GetProductDetailsById?ProductId=" + GetProduct.ProductId);
                if (response.code == 200)
                {
                    Product = JsonConvert.DeserializeObject<List<InvoiceDetailsViewModel>>(response.data.ToString());
                    Product.ForEach(a => a.ProductTotal = (a.PerUnitPrice ?? 0) + (a.GstAmount ?? 0));
                }
                return PartialView("~/Views/Invoice/_DisplayInvoiceProductDetailsPartial.cshtml", Product);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public IActionResult GenerateInvoice(InvoiceViewModel data)
        {
            return Json(data);
        }

        [HttpGet]
        public async Task<IActionResult> GenerateInvoicePDF()
        {
            return View();
        }

        [FormPermissionAttribute("InvoiceDetails-View")]
        public async Task<IActionResult> OrderInvoiceDetails(string OrderId)
        {
            try
            {
                string porjectname = UserSession.ProjectName;
                ApiResponseModel Response = await APIServices.GetAsync("", "Invoice/CheckInvoiceNo?porjectname=" + porjectname);
                List<PurchaseOrderDetailView> order = new List<PurchaseOrderDetailView>();
                ApiResponseModel response = await APIServices.GetAsync("", "Invoice/GetInvoiceDetailsByOrderId?OrderId=" + OrderId);
                if (response.code == 200)
                {
                    order = JsonConvert.DeserializeObject<List<PurchaseOrderDetailView>>(response.data.ToString());
                    response.data = order;
                }
                if (Response.code == 200)
                {
                    ViewBag.InvoiceNo = Response.data;
                }
                return View(order);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [FormPermissionAttribute("DisplayInvoiceDetails-View")]
        public async Task<IActionResult> InvoiceDetails(Guid InvoiceId)
        {
            try
            {
                InvoiceMasterModel invoice = new InvoiceMasterModel();
                ApiResponseModel response = await APIServices.GetAsync("", "Invoice/DisplayInvoiceDetailsById?Id=" + InvoiceId);
                if (response.code == 200)
                {
                    invoice = JsonConvert.DeserializeObject<InvoiceMasterModel>(response.data.ToString());

                    decimal? number, gstamt;

                    if (invoice.DollarPrice != 0)
                    {
                        number = invoice.TotalAmount * invoice.DollarPrice.Value;
                        gstamt = invoice.TotalGst * invoice.DollarPrice.Value;
                    }
                    else
                    {
                        number = invoice.TotalAmount;
                        gstamt = invoice.TotalGst;
                    }

                    var totalAmountInWords = NumberToWords((decimal)number);
                    ViewData["TotalAmountInWords"] = totalAmountInWords + " " + "Only";

                    var totalGstInWords = NumberToWords((decimal)gstamt);
                    ViewData["TotalGstInWords"] = totalGstInWords + " " + "Only";
                }
                return View(invoice);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public static string NumberToWords(decimal number)
        {
            int integerPart = (int)Math.Floor(number);
            decimal decimalPart = number - integerPart;

            string words = "";

            if (integerPart == 0)
            {
                words = "zero";
            }
            else if (integerPart < 0)
            {
                words = "minus " + NumberToWords(Math.Abs(integerPart));
            }
            else
            {
                if ((integerPart / 1000000) > 0)
                {
                    words += NumberToWords(integerPart / 1000000) + " million ";
                    integerPart %= 1000000;
                }

                if ((integerPart / 1000) > 0)
                {
                    words += NumberToWords(integerPart / 1000) + " thousand ";
                    integerPart %= 1000;
                }

                if ((integerPart / 100) > 0)
                {
                    words += NumberToWords(integerPart / 100) + " hundred ";
                    integerPart %= 100;
                }


                if (integerPart > 0)
                {
                    var unitsMap = new[] { "zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen" };
                    var tensMap = new[] { "zero", "ten", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety" };

                    if (words != "")
                        words += " ";

                    if (integerPart < 20)
                        words += unitsMap[integerPart];
                    else
                    {
                        words += tensMap[integerPart / 10];
                        if ((integerPart % 10) > 0)
                            words += "-" + unitsMap[integerPart % 10];
                    }
                }
            }

            if (decimalPart > 0)
            {
                decimalPart *= 100;
                words += " and " + NumberToWords((int)decimalPart) + " paisa";
            }

            return words;
        }

        [HttpGet]
        public async Task<IActionResult> GetInvoiceDetailsByOrderId(string OrderId)
        {
            try
            {
                ApiResponseModel response = await APIServices.GetAsync("", "Invoice/GetInvoiceDetailsByOrderId?OrderId=" + OrderId);
                if (response.code == 200)
                {

EMPManegment.WebApplication/Views/Invoice/AllTransaction.cshtml
@using EMPManegment.Web.Models;
@inject IHttpContextAccessor Accessor;
@inject UserSession _userSession

@{
    ViewData["Title"] = "GetAllTransaction";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}
<link href="~/assets/css/icons.min.css" rel="stylesheet" type="text/css" />

<div class="row" style="margin-top:80px;">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="mb-sm-0">Transactions List</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Payment Transactions</a></li>
                    <li class="breadcrumb-item active">GetAllTransction</li>
                </ol>
            </div>

        </div>
    </div>
</div>
<!-- end page title -->


<div class="row" id="contactList">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex align-items-center border-0">
                <h5 class="card-title mb-0 flex-grow-1">Vendor Transactions</h5>
            </div>
            <div class="card-body border border-dashed border-end-0 border-start-0">
                <div class="row g-2">
                    <div class="col-xl-4 col-md-6">
                        <div class="search-box">
                            <input type="text" class="form-control search" id="searchcreditdebitlist" placeholder="Search...">
                            <i class="ri-search-line search-icon"></i>
                        </div>
                    </div>
                    <!--end col-->
                    <div class="col-xl-3 col-md-6">
                        <select class="form-control" id="textTransactionCompanyName">
                            <option value="AllCompany">All Company</option>
                        </select>
                    </div>
                    <!--end col-->
                    <div class="col-xl-2 col-md-4">
                        <div class="input-group">
                            <input type="date" class="form-control" id="vendorstartdate">
                        </div>
                    </div>
                    <!--end col-->
                    <div class="col-xl-2 col-md-4">
                        <div class="input-group">
                            <input type="date" class="form-control" id="vendorenddate">
                        </div>
                    </div>
                    <!--end col-->
                    <div class="col-xl-1 col-md-4">
                        <button class="btn btn-primary w-100" onclick="SearchDatesInVendorCreditDebitList();">Search</button>
                    </div>
                </div>
                <!--end row-->
            </div>
            <div class="card-body p-0">
                <div class="card-body">
                    <div class="table-responsive table-card text-center">
                        <table class="table table-bordered dt-responsive nowrap table-striped align-middle" id="AllVendorCreditDebitList">
                            <thead class="btn-info text-center">
                                <tr>
                                    <th></th>
                                    <th>Vendor Name</th>
                                    <th>Date</th>
                                    <th>Payment Type</th>
                                    <th>Credit Amount</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody class="list form-check-all" id="AllTransactionPartial">
                            </tbody>
                        </table>
                        <!--end table-->
                        <div class="noresult" style="display: none">
                            <div class="text-center">
                                <lord-icon src="https://cdn.lordicon.com/msoeawqm.json" trigger="loop" colors="primary:#25a0e2,secondary:#00bd9d" style="width:75px;height:75px">
                                </lord-icon>
                                <h5 class="mt-2">Sorry! No Result Found</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--end card-->
    </div>
    <!--end col-->
</div>

<script type="text/javascript">
    var userPermissions = '@Html.Raw(Json.Serialize(UserSession.FormPermisionData))';
</script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/moduls/creditdebitmasterscript.js" asp-append-version="true"></script>

EMPManegment.WebApplication/Views/Invoice/InvoiceListView.cshtml
@model List<EMPManegment.EntityModels.ViewModels.Invoice.InvoiceViewModel>
@using EMPManegment.Web.Models;
@inject IHttpContextAccessor Accessor;
@inject UserSession _userSession

@{
    ViewData["Title"] = "InvoiceListView";
    Layout = "~/Views/Shared/_UserHomeLayout.cshtml";
}

<!-- start page title -->
<div class="row" style="margin-top:80px;">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="mb-sm-0">Invoice List</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Invoices</a></li>
                    <li class="breadcrumb-item active">InvoicesListView</li>
                </ol>
            </div>

        </div>
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-lg-12">
        <div class="card" id="invoiceList">
            <div class="card-header border-0">
                <div class="d-flex align-items-center">
                    <h5 class="card-title mb-0 flex-grow-1">Invoices</h5>
                    @if (UserSession.FormPermisionData.Any(a => a.FormName == "Create Invoice" && (a.Add == true)))
                    {
                        <div class="flex-shrink-0">
                            <div class="d-flex gap-2 flex-wrap">
                            <a asp-action="CreateInvoice" asp-controller="Invoice" class="btn btn-info"><i class="ri-add-line align-bottom me-1"></i>Invoice</a>
                            </div>
                        </div>
                    }
                </div>
            </div>

            <div class="card-body">
                <div class="listjs-table">
                    <div class="table-responsive">
                        <table id="invoiceTable" class="table table-bordered dt-responsive nowrap table-striped align-middle dataTable no-footer dtr-inline">
                            <thead class="table-info text-muted text-center">
                                <tr class="text-center">
                                    <th>InvoiceNo</th>
                                    <th>VendorName</th>
                                    <th>ProjectName</th>
                                    <th>TotalAmount</th>
                                    @if (UserSession.FormPermisionData.Any(a => a.FormName == "InvoiceListView" && (a.Edit == true || a.Delete == true)))
                                    {
                                        <th>Action</th>
                                    }
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                        <div class="noresult" style="display: none">
                            <div class="text-center">
                                <lord-icon src="https://cdn.lordicon.com/msoeawqm.json" trigger="loop" colors="primary:#25a0e2,secondary:#00bd9d" style="width:75px;height:75px">
                                </lord-icon>
                                <h5 class="mt-2">Sorry! No Result Found</h5>
                                <p class="text-muted mb-0">
                                    We've searched more than 150+ transactions We did not find any
                                    transactions for you search.
                                </p>
                            </div>
                        </div>
                        <!-- end table -->
                    </div>
                </div>
                <!-- container-fluid -->
            </div>
        </div>

        <!--Update Invoice Modal -->
        <div class="modal fade" id="UpdateInvoiceModel" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header bg-light p-3">
                        <h5 class="modal-title" id="exampleModalLabel">Update Invoice</h5><h5 class="modal-title" id="txtinvoiceno" style="margin-left:10px;"></h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" id="close-modal"></button>
                    </div>
                    <form class="tablelist-form" autocomplete="off" id="UpdateInvoiceDetailsForm">
                        <div class="modal-body">

                            <div class="mb-3">
                                <label for="date-field" class="form-label">Invoice Date</label>
                                <input type="datetime-local" data-date-format="d M, Y" data-enable-time id="txtinvoicedate" name="txtinvoicedate" class="form-control" />
                                <input type="hidden" id="txtid" class="form-control" />
                            </div>

                            <div class="mb-3">
                                <label for="customername-field" class="form-label">Company Name</label>
                                <input type="text" id="txtcompanyname" name="txtcompanyname" class="form-control" placeholder="Enter Company name" />
                            </div>

                            <div class="row gy-4 mb-3">
                                <div class="col-md-6">
                                    <div>
                                        <label for="amount-field" class="form-label">Amount</label>
                                        <input type="text" id="txtamount" name="txtamount" class="form-control" placeholder="Total amount" />
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div>
                                        <label for="payment-field" class="form-label">Payment Method</label>
                                        <select class="form-control" data-trigger name="txtpaymentmethod" id="txtpaymentmethod">
                                            <option selected disabled value="">---Select Payment Method---</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="row gy-4 mb-3">
                                <div class="col-md-6">
                                    <div>
                                        <label for="payment-field" class="form-label">Status</label>
                                        <select class="form-control" data-trigger name="txtstatus" id="txtstatus">
                                            <option selected disabled value="">Select Status</option>
                                            <option value="Pending">Pending</option>
                                            <option value="Confirm">Confirm</option>
                                            <option value="Complete">Complete</option>
                                            <option value="Cancel">Cancel</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <div class="hstack gap-2 justify-content-end">
                                <button type="button" class="btn btn-danger btn-default m-1" id="close-modal" data-bs-dismiss="modal">Close</button>
                                <button type="button" class="btn btn-success" onclick="UpdateInvoiceDetails()" id="updatedetailbtn">Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!--end modal -->
    </div>
</div>

<!--end col-->
<!-- end row-->
<!--end row-->
<style>
    #txtinvoicedate-error, #txtcompanyname-error, #txtamount-error,
    #txtpaymentmethod-error, #txtstatus-error {
        color: red;
    }
</style>
<script type="text/javascript">
    var userPermissions = '@Html.Raw(Json.Serialize(UserSession.FormPermisionData))';
</script>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/moduls/invoicemasterscript.js" asp-append-version="true"></script>

EMPManegment.WebApplication/Views/Invoice/Invoices.cshtml
@model List<EMPManegment.EntityModels.ViewModels.Invoice.InvoiceViewModel>
@using EMPManegment.Web.Models;
@inject IHttpContextAccessor Accessor;
@inject UserSession _userSession

@{
    ViewData["Title"] = "InvoiceListView";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<!-- start page title -->
<div class="row" style="margin-top:80px;">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="mb-sm-0">Invoice List</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Invoices</a></li>
                    <li class="breadcrumb-item active">InvoicesListView</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-lg-12">
        <div class="card" id="invoiceList">
            <div class="card-header">
                <div class="d-flex align-items-center">
                    <h5 class="card-title mb-0 flex-grow-1">Invoices</h5>
                    <input hidden id="txtInvoice" type="text" value="@UserSession.ProjectId" />
                    @if (UserSession.FormPermisionData.Any(a => a.FormName == "Create Invoice" && (a.Add == true)))
                    {
                        <div class="flex-shrink-0">
                            <div class="d-flex gap-2 flex-wrap">
                                <button class="btn btn-info" onclick="createInvoice()"><i class="ri-add-line align-bottom me-1"></i>Invoice</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="card-body">
                <div class="listjs-table">
                    <div class="table-responsive">
                        <table id="invoiceTable" class="table table-bordered dt-responsive nowrap table-striped align-middle dataTable no-footer dtr-inline">
                            <thead class="btn-info text-center">
                                <tr class="text-center">
                                    <th>InvoiceNo</th>
                                    <th>VendorName</th>
                                    <th>ProjectName</th>
                                    <th>TotalAmount</th>
                                    @if (UserSession.FormPermisionData.Any(a => a.FormName == "InvoiceListView" && (a.Edit == true || a.Delete == true)))
                                    {
                                        <th>Action</th>
                                    }
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                        <div class="noresult" style="display: none">
                            <div class="text-center">
                                <lord-icon src="https://cdn.lordicon.com/msoeawqm.json" trigger="loop" colors="primary:#25a0e2,secondary:#00bd9d" style="width:75px;height:75px">
                                </lord-icon>
                                <h5 class="mt-2">Sorry! No Result Found</h5>
                                <p class="text-muted mb-0">
                                    We've searched more than 150+ transactions We did not find any
                                    transactions for you search.
                                </p>
                            </div>
                        </div>
                        <!-- end table -->
                    </div>
                </div>
                <!-- container-fluid -->
            </div>
        </div>
        <!--Update Invoice Modal -->
        <div class="modal fade" id="UpdateInvoiceModel" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header bg-light p-3">
                        <h6 class="modal-title" id="exampleModalLabel">Update Invoice</h6><h7 class="modal-title" id="txtinvoiceno" style="margin-left:30px;"></h7>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" id="close-modal"></button>
                    </div>
                    <form class="tablelist-form" autocomplete="off" id="UpdateInvoiceDetailsForm">
                        <div class="modal-body">
                            <div class="mb-3">
                                <label for="date-field" class="form-label">Invoice Date</label>
                                <input type="datetime-local" data-date-format="d M, Y" data-enable-time id="txtinvoicedate" name="txtinvoicedate" class="form-control" />
                                <input type="hidden" id="txtid" class="form-control" />
                                <input type="hidden" id="txtUpdatedBy" value="@_userSession.UserId" />
                            </div>

                            <div class="mb-3">
                                <label for="customername-field" class="form-label">Company Name</label>
                                <input type="text" id="txtcompanyname" name="txtcompanyname" class="form-control" placeholder="Enter Company name" />
                            </div>

                            <div class="row gy-4 mb-3">
                                <div class="col-md-6">
                                    <div>
                                        <label for="amount-field" class="form-label">Amount</label>
                                        <input type="text" id="txtamount" name="txtamount" class="form-control" placeholder="Total amount" />
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div>
                                        <label for="payment-field" class="form-label">Payment Method</label>
                                        <select class="form-control" data-trigger name="txtpaymentmethod" id="txtpaymentmethod">
                                            <option selected disabled value="">---Select Payment Method---</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row gy-4 mb-3">
                                <div class="col-md-6">
                                    <div>
                                        <label for="payment-field" class="form-label">Status</label>
                                        <select class="form-control" data-trigger name="txtstatus" id="txtstatus">
                                            <option selected disabled value="">Select Status</option>
                                            <option value="Pending">Pending</option>
                                            <option value="Confirm">Confirm</option>
                                            <option value="Complete">Complete</option>
                                            <option value="Cancel">Cancel</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <div class="hstack gap-2 justify-content-end">
                                <button type="button" class="btn btn-danger btn-default m-1" id="close-modal" data-bs-dismiss="modal">Close</button>
                                <button type="button" class="btn btn-success" onclick="UpdateInvoiceDetails()" id="updatedetailbtn">Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!--end modal -->
    </div>
</div>
<!--end row-->
<script type="text/javascript">
    var userPermissions = '@Html.Raw(Json.Serialize(UserSession.FormPermisionData))';
</script>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/moduls/invoicemasterscript.js" asp-append-version="true"></script>
<script src="~/moduls/purchaseorderdetailsscript.js" asp-append-version="true"></script>